"""empty message

Revision ID: 9034372b757d
Revises: f91ac85e9fc0
Create Date: 2023-09-30 09:56:14.062896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9034372b757d'
down_revision = 'f91ac85e9fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_comment_post_id_fkey', 'post_comment', type_='foreignkey')
    op.drop_constraint('post_comment_comment_id_fkey', 'post_comment', type_='foreignkey')
    op.create_foreign_key(None, 'post_comment', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_comment', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_likes_post_id_fkey', 'post_likes', type_='foreignkey')
    op.drop_constraint('post_likes_like_id_fkey', 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'likes', ['like_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key('post_likes_like_id_fkey', 'post_likes', 'likes', ['like_id'], ['id'])
    op.create_foreign_key('post_likes_post_id_fkey', 'post_likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_comment', type_='foreignkey')
    op.drop_constraint(None, 'post_comment', type_='foreignkey')
    op.create_foreign_key('post_comment_comment_id_fkey', 'post_comment', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key('post_comment_post_id_fkey', 'post_comment', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
